Added Convert Custom sample
Euclideon/vaultsdksamples pull request #6
Opened 2020-02-21 03:05 UTC by OsiJr

2020-02-21 03:06 UTC, OsiJr commented on features/convertcustomdata/README.md
> +2. Set User information in
Didn't finish this section...

2020-02-21 03:12 UTC, samsinsane requested changes

2020-02-21 03:12 UTC, samsinsane commented on features/convertcustomdata/README.md
> +Toolsets:              C99 or MSVC compiler
It's a C++ sample.

2020-02-21 03:12 UTC, samsinsane commented on features/convertcustomdata/project.lua
> +		buildoptions { "-std=c99" }
I'm fairly certain this is going to cause problems while compiling.

2020-03-20 01:28 UTC, samsinsane approved these changes

2020-03-20 01:28 UTC, merged